[tool.poetry]
name = "playwrightdock"
version = "0.1.0"
description = ""
authors = ["fauzaanu <hello@fauzaanu.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
playwright = "^1.46.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
